### ISSUE TITLE
FormModel _.has(formModel, 'url') returning false when checking for "url" field when it is a method.

### ISSUE THREAD

**Issue by kentmw** [vecnatechnologies/backbone-torso#112]
Looks like methods defined in a form model exist only in the ```__proto__``` field so _.has does not catch it (it's not nested).

https://github.com/vecnatechnologies/backbone-torso/blob/master/modules/FormModel.js#L226

**Comment by kentmw** [comment]
The workaround for now is sadly to do:
```
this.model.url = this.model.url;
```
I kid you not...

**Comment by mandragorn** [comment]
Why are you using _.has instead of checking if the property is accessible from the object.

if (formModel.url)

or something more complicated using !== 'undefined' and !== null

**Comment by kentmw** [comment]
No reason. That's probably the better move.

**Comment by andyhuang91** [comment]
From the underscore documentation for `_.has`

>Does the object contain the given key? Identical to object.hasOwnProperty(key), but uses a safe reference to the hasOwnProperty function, in case it's been overridden accidentally.

The underscore method is doing exactly what it's supposed to. As Josh said, what you really want to check for is `if (formModel.url)`

`__proto__` is not a real property on JavaScript objects. That's just how chrome prints out the `[[Prototype]]` that an object delegates to. You should not try to do `this.model.url = this.model.url;` because that circumvents the prototype based inheritance pattern built into JavaScript

**Comment by kentmw** [comment]
@andyhuang91, I was only providing a work around, not a best practice. It should of course be fixed

**Comment by andyhuang91** [comment]
@kentmw Just trying to clarify what's actually going on. When you call backbone's `extend` method, properties and methods are added to a new prototype object and a constructor is returned. The wording in the original comment was kind of weird (it mentions a `__proto__` "field" and things being "nested")
