### ISSUE TITLE
ListView createChildView does not use modelId option

### ISSUE THREAD

**Issue by kentmw** [vecnatechnologies/backbone-torso#127]
https://github.com/vecnatechnologies/backbone-torso/blob/master/modules/ListView.js#L326

the getter does, but the setter is hard coded to model.cid.

This leads to errors if you try to update it away from cid.

**Comment by mandragorn** [comment]
what is the use case of using something other than the cid of the model?  When you want to display the same model in a list multiple times?  Until I see a real-world use-case it looks like unneeded complexity.  __modelId is poorly named because I would think that it identifies the id property of the model object, not a unique identifier in the collection's list of models.

**Comment by kentmw** [comment]
modelId is the attribute on the model that uniquely identifies it to the list view. If there is no classic "id" to a model, then any fetches to the server creates new models and therefore creates new views. If a model has not registered an "idAttribute" then new models will be created on every fetch. I guess that the problem could be solved on the model level instead of the view level. I can't think right now of any other use cases for modelId.

**Comment by mandragorn** [comment]
oh, so it does replace idAttribute?  I think it makes sense to be consistent with Backbone and force implementations to set idAttribute correctly.

**Comment by kentmw** [comment]
@mandragorn, see my edit above for clarification.
