### ISSUE TITLE
Initialize should always be called after the constructor

### ISSUE THREAD

**Issue by Earthstar** [vecnatechnologies/backbone-torso#195]
Right now, ListView calls View.apply at the beginning of the constructor. This can cause bugs when a view inheriting from ListView has an initialize method which relies on fields which are initialized in the ListView constructor.

In general, Torso classes should be written such that initialize is always called after the constructor.

**Comment by kentmw** [comment]
In general, I agree, but I do worry about timing on chaining inheritance. I think ListView and FormView constructors don't have access to View's constructed variables (feedbackCell, viewState, etc.) until View.apply is run.

We can move ListView's View.apply to the bottom of the constructor because it doesn't rely on View's constructed variables but it's not as easy as just remembering to call View.apply at the bottom.

**Comment by kentmw** [comment]
Just ran into this issue: You can't redefine a FormView's FormModel in the initialize method without also redefining the this.listenTo(this.model, ...) blocks.

It seems like it would be better to define the this.listenTo(this.model ...) blocks after the View.apply - that way you can be sure the model is the correct form model before attaching listeners to it.

**Comment by mandragorn** [comment]
that sounds correct.

**Comment by kentmw** [comment]
#210 was created for FormView's exception to this issue.

**Comment by kentmw** [comment]
Actually, this just isn't true generally speaking. There are things that should be handled after initialize method and there are things that should be handled before. State that needs to be set before initialize should be before the apply. Closing this issue as too general. Please open issues that target specific issues.
