### ISSUE TITLE
Does new render logic need to handle multiple templates?

### ISSUE THREAD

**Issue by kentmw** [vecnatechnologies/backbone-torso#207]
Some projects are using multiple templates to define different components of their DOM. Should we support this? Should we suggest multiple views in this case? or use partials?

**Comment by mandragorn** [comment]
I've been having a lot of cases recently where I have a view with all the logic I need, but I want to style it slightly differently (i.e. for an admin user vs. patient) which causes me to create a lot of css class switches and in some cases different DOM elements.

Partials have been problematic in the past and there is something about browserify not fully supporting them (they are not processed correctly by quick-sip).

I'm not sure if multiple views or templates are better.  But for generality multiple templates are probably good to support.  Would it make sense to have a template context property reserved for choosing the template so that the logic for generating the template context and determining the template to use are all in one place (prepare())?  We could default the property to the view's template to reserve the use of the property.

**Comment by kentmw** [comment]
@mandragorn added a pull request for this. I think it just makes sense to allow people to put in whatever dom update logic they want.

**Comment by kentmw** [comment]
open ```updateDOM``` to be overridable,
