### ISSUE TITLE
Configuring Torso shouldn't be this awkward

### ISSUE THREAD

**Issue by arikwex** [vecnatechnologies/backbone-torso#39]
var Torso = require('backbone-torso');
require('backbone-torso/node_modules/backbone').$ = $;
Torso.$ = $;

maybe we could have:
var _ = require('your underscore');
var $ = require('your jquery');
var Torso = require('backbone-torso');
Torso.configure(_, $);

**Comment by kentmw** [comment]
Torso.$ = $ is not needed right now

**Comment by kentmw** [comment]
Do this in factory in each module?

**Comment by kentmw** [comment]
Configure module?

**Comment by kentmw** [comment]
Going to make a module called "configure"

It will grab backbone and jquery and set backbone's $ to jquery or root's $.

I will put this on the torso bundle to run automatically in browserify and require.
```
require("backbone-torso");
```
Or if you are just bringing in modules:
```
require('backbone-torso/modules/configure');
```

In global namespace with torso bundle, you don't have to do anything because configure will run automatically as long as jquery and backbone were already imported on the page.

In global namespace without torso bundle, you just have to import that "configure" module on to your page after bringing in jquery and backbone:
```
<script src="backbone-torso/modules/configure">
```

**Comment by kentmw** [comment]
See previous comment for configuring torso

**Comment by diokey** [comment]
````html 
<script src="backbone-torso/modules/configure">
````
Sticking jquery in the global namespace can cause some conflict with some other libraries. 
Sometimes we are using torso on a page that uses prototype.js and the $ sign will always conflict.

**Comment by kentmw** [comment]
This is true, but the configure module just sets Backbone.$ = $; and nothing more.

generator-torso-brec will add $ to the window object which could cause conflicts - but because that project is starting from scratch you can safely assume that won't be the case.
